name: steps examples

on:
  push:
    branches: ["main"]

jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14
      - name: verification of node version
        run: node --version
